### PR TITLE
NGSTACK-789 add extensions array option

### PR DESCRIPTION
**Pull request by amalija-ramljak**
Instead of hardcoded single `js` extension, the action takes an `"extensions": []` option to allow for other possible JS extensions - jsx, ts, tsx.

### CODE REVIEW

**Comment by emodric** [comment]
Looks good, apart from CS fixer failure.

**Comment by iherak** [comment]
@amalija-ramljak @emodric what's the status here? A bit forgotten? :)

**Comment by amalija-ramljak** [comment]
Hm, the thing that's now failing in CS Fixer is something that is written the same in the PHP actions from what I can see, should I change it to what it recommends and use the appropriate namespace? @emodric 

```
-    public function execute(Config $config, IO $io, Repository $repository, Config\Action $action): void
+    public function execute(Config $config, IO $io, Repository $repository, ActionConfig $action): void
```

**Comment by emodric** [comment]
It's probably the same failure as before, but we cannot confirm as obsolete logs are removed.

Please add a proper `use` statement everywhere where needed and change `Config\Action` to `ActionConfig` as suggested.

**Comment by emodric** [comment]
Thanks @amalija-ramljak !

**Pull request merged**
